POST http://localhost:5175/api/newFollower
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsImtpZCI6IllIWUYraE1PcmZXTFFzdHciLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FiYW10ZWd6aXF1YmZpaWN5ZnRjLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJmZDQzOTY0MC03Nzg1LTQ2OTQtOWY2Ni1lYTYxMzJlNTA4MjEiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzUxMzE2NTYzLCJpYXQiOjE3NTEyMTY1NjMsImVtYWlsIjoieGFuZGVyYnJvd24wNUBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsIjoieGFuZGVyYnJvd24wNUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGhvbmVfdmVyaWZpZWQiOmZhbHNlLCJzdWIiOiJmZDQzOTY0MC03Nzg1LTQ2OTQtOWY2Ni1lYTYxMzJlNTA4MjEiLCJ1c2VybmFtZSI6InhhbmRlcmJyb3duMDUifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc1MTIxNjU2M31dLCJzZXNzaW9uX2lkIjoiNThkYTUzMzMtZjVmZi00YmRjLTlkMTMtMTQ0NTFjODQzMDdhIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.onpY85-PJbKVkO05IJVvHgZUs5VEiseQAaeX7GHLy-M

{
    "targetUserName": "tash"
}